# ./.github/actions/docker-action/action.yml
name: 'Docker Action'
description: 'Do something with Docker'
inputs:
  host:
    description: 'Host for locust to run off of'
    required: true
  locustfile:
    description: 'Path to the locust file'
    required: true
  users:
    description: 'Number of concurrent users for the test'
    required: true
  spawn-rate:
    description: 'Rate per second in which users are spawned'
    required: true
  run-time:
    description: 'Test run duration. E.g., 20s, 3m, 1h'
    required: true
outputs:
  JSON_DIR:
    description: 'Directory where JSON results are stored'
  CURR_TIME:
    description: 'Current time when the test was executed'
runs:
  using: 'docker'
  image: 'Dockerfile'