# npm install @actions/core @actions/github @actions/exec
name: 'JavaScript Action'
description: 'Do something with JavaScript'
inputs:
    # Input values can be used in JS code
    locustfile:
        description: "Locust file to run the test on"
        required: true
    users:
        description: "How many users"
        required: true
    spawn-rate:
        description: "How many users to hatch at a time"
        required: true
    run-time:
        description: "How long to run for"
        required: true
outputs:
    JSON_DIR:
        description: 'Directory for the JSON output'
    CURR_TIME:
        description: 'The current time stamp that the locust test was run'
    json-cleaned:
        description: 'A boolean response of whether it has been cleaned or not.'
runs:
    using: 'node16'
    main: 'main.js'
