name: 'Run locust'
description: 'Run locust command with specifications'
inputs:
  locustfile:
    description: "Which locust test file to run"
    required: true
  users:
    description: "How many users"
    required: true
  spawn-rate:
    description: "How many users to hatch at a time"
    required: true
  run-time:
    description: "How long to run for"
    required: false
    default: '60s'
runs:
  using: 'composite'
  steps:
    # Run locust test and output results
    - name: Run locust test
      shell: bash
      run: |
        source .venv/bin/activate
        CURR_TIME=$(date +%Y-%m-%d_%Hh-%Mm-%Ss)
        LOG_DIR="./logfiles"
        HTML_DIR="./htmlfiles"
        CSV_DIR="./csvfiles/$CURR_TIME"
        JSON_DIR="./jsonfiles/$CURR_TIME"

        mkdir -p $LOG_DIR $HTML_DIR $CSV_DIR $JSON_DIR

        echo "JSON_PATH=./jsonfiles/$CURR_TIME" >> $GITHUB_ENV
        echo "CURR_TIME=$CURR_TIME" >> $GITHUB_ENV

        locust \
          -f ${{ inputs.locustfile }} \
          --users ${{ inputs.users }} \
          --spawn-rate ${{ inputs.spawn-rate }} \
          --run-time ${{ inputs.run-time }} \
          --headless \
          --logfile $LOG_DIR/$(echo $CURR_TIME)_mylog.log --loglevel INFO \
          --html $HTML_DIR/$(echo $CURR_TIME)_myhtml.html \
          --csv $CSV_DIR/$(echo $CURR_TIME) --csv-full-history \
          --json \
          --exit-code-on-error 1 \
          --only-summary | awk '/\[/{flag=1} flag; /\]/{flag=0; print}' > $JSON_DIR/$(echo $CURR_TIME).json

        unset CURR_TIME LOG_DIR HTML_DIR CSV_DIR JSON_DIR
