  name: 02-Reusable_Flow
  on:
    workflow_call:
      inputs:
        # Take input from workflow that calls this reusable workflow
        artifact-name:
          type: string
          description: The name of the locust output file
          required: true
      secrets:
        little-secret:
          required: true
      outputs:
        result:
          description: The result of the second-job operation
          # Value is taken from the steps of the job
          value: ${{ jobs.second-job.outputs.outcome }}
  jobs:
    second-job:
      outputs:
        outcome: ${{ steps.set-result.outputs.step-result }}
      runs-on: self-hosted
      steps:
        - name: Say something
          run: echo "This is the second job!"

        # Download artifacts
        - name: Get artifacts
          # needs.<JOB_NAME>.steps.<STEP_ID>.outcome
          uses: actions/download-artifact@v3
          with:
            name: ${{ inputs.artifact-name }}

        - name: List logs and tell me a little secret
          run: | 
            ls ./logfiles
            # Uses little-secret passed from previous workflow
            echo "${{ secrets.little-secret }}"

        - name: Set result output
          id: set-result
          run: echo "step-result=success" >> $GITHUB_OUTPUT
#
#        # Echo outputs from 'test' job
#        - name: Output filename
#          run: |
#            echo "${{ needs.test.outputs.script-file }}"
#            echo "${{ needs.test.outputs.png-file }}"
#            echo "${{ needs.test.outputs.UPLOAD_ARTIFACTS }}"
#            echo "${{ needs.test.steps.upload_step.outcome }}"

  # We want to run this workflow within another workflow. This is why it is called a 'reusable workflow'