name: Activity Types Tests
on:
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
  push:
    branches:
      - main
      # Wildcard notations available
      - 'dev-*'
      - 'feat/**'
    paths:
      - '.github/workflows/*' # if no file changed in the github folder, then don't do anything
  pull_request:
    types:
      - opened
      - closed
  issue_comment:
    types:
      - created # when an issue comment is created, updated, deleted -- this applies to pull request comments too
      - edited
      - deleted
  workflow_dispatch:
jobs:
  print-text:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "Hello World!"
          echo "Hello again, World!"
      - name: Print goodbye
        run: |
          echo "Done - bye!"
          echo "Woops, forgot something. Ok, bye now!"

      - name: "Print Issue object"
        run: echo "${{ toJson(github.event.issue) }}"

  print-conditional-text:
    runs-on: ubuntu-latest
    if: ${{github.event.issue.pull_request}}
    steps:
      - name: "Conditional Printer: Pull Request Comment"
        run: |
          echo "This is printing because a pull request comment was made."

      - name: "Print Issue object"
        run: echo "${{ toJson(github.event.issue) }}"

      - name: "Print Issue object's PR"
        run: echo "${{ toJson(github.event.issue.pull_request) }}"

# default activity types for pull_request == 'opened', 'synchronize' or 'reopened'