name: Activity Types Tests
on:
  pull_request:
    types:
      - opened
      - closed
  issue_comment:
    types:
      - created
      - edited
      - deleted
  workflow_dispatch:
jobs:
  print-text:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "Hello World!"
          echo "Hello again, World!"
      - name: Print goodbye
        run: |
          echo "Done - bye!"
          echo "Woops, forgot something. Ok, bye now!"

  print-conditional-text:
    runs-on: ubuntu-latest
    if: ${{github.event.issue.pull_request}}
    steps:
      - name: "Conditional Printer: Pull Request Comment"
        run: |
          echo "This is printing because a pull request comment was made."

      - name: "Print Issue object"
        run: echo "${{ github.event.issue }}"

      - name: "Print Issue object's PR"
        run: echo "${{ github.event.issue.pull_request }}"

# default activity types for pull_request == 'opened', 'synchronize' or 'reopened'