# ./.github/workflows/docker-action.yml
name: Docker Actions Test
run-name: ${{ github.actor }} is testing out Custom Docker Action 🚀
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: # if activity in this folder or file, permitted. paths-ignore is the opposite
      - '.github/workflows/docker-action.yml'
      - '.github/actions/docker-action'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      UPLOAD_ARTIFACTS: true
    steps:
      # Get code from repo
      - name: Get code
        uses: actions/checkout@v3

      # NOTE: Docker action here - unable to get upload artifacts to work within the container
      - name: Run custom docker action for a locust test run
        id: docker-runner
        uses: ./.github/actions/docker-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # NOTE: locustfile.py was created to conform to this docker action, slight mod on it with getting host input
          host: 'https://smallbra.in'
          # NOTE: File was put in local so Dockerfile can grab it
          locustfile: 'locustfile.py'
          users: 2
          spawn-rate: 1
          run-time: 2s

      - name: Print the CURR_TIME outputs"
        run: |
          echo "The locust test was started at this time: ${{ steps.docker-runner.outputs.CURR_TIME }}"