name: DOCKER FLOW
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: # if activity in this folder or file, permitted. paths-ignore is the opposite
      - '.github/workflows/docker-flow.yml'
jobs:
  testing-one:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t my-locust-image -f ./Dockerfile .

      - name: Start Docker Compose
        run: docker compose -f ./docker-compose.yml up --no-build

  testing-two:
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          source .venv/bin/activate
          pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          CURR_TIME=$(date +%Y-%m-%d_%Hh-%Mm-%Ss)
          LOG_DIR="./logfiles"
          HTML_DIR="./htmlfiles"
          CSV_DIR="./csvfiles/$CURR_TIME"
          JSON_DIR="./jsonfiles/$CURR_TIME"

          mkdir -p $LOG_DIR
          mkdir -p $HTML_DIR
          mkdir -p $CSV_DIR
          mkdir -p $JSON_DIR

          echo "JSON_PATH=./jsonfiles/$CURR_TIME" >> $GITHUB_ENV
          echo "CURR_TIME=$CURR_TIME" >> $GITHUB_ENV

          locust \
            -f locustfiles/test.py \
            --users 25 \
            --spawn-rate 5 \
            --run-time 5s \
            --headless \
            --logfile $LOG_DIR/$(echo $CURR_TIME)_mylog.log --loglevel INFO \
            --html $HTML_DIR/$(echo $CURR_TIME)_myhtml.html \
            --csv $CSV_DIR/$(echo $CURR_TIME) --csv-full-history \
            --json \
            --exit-code-on-error 1 \
            --only-summary | awk '/\[/{flag=1} flag; /\]/{flag=0; print}' > $JSON_DIR/$(echo $CURR_TIME).json

          unset CURR_TIME LOG_DIR HTML_DIR CSV_DIR

    # Upload artifacts
      - name: Upload artifacts
        id: upload_step
        if: env.UPLOAD_ARTIFACTS == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: locust-output-files
          path: |
            ./logfiles/
            ./htmlfiles/
            ./csvfiles/
            ./jsonfiles/