name: GitHub Actions Workflow Email Test
on: [workflow_dispatch] # can add more than one event trigger
jobs:
  standard:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{secrets.MAIL_SERVER}}
          server_port: ${{secrets.MAIL_PORT}}
          secure: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions Workflow Started + Attachment
          to: ${{ env.EMAIL_TO }}
          from: ${{ env.EMAIL_FROM }}
          body: ${{ env.EMAIL_BODY }}
          attachments: ${{ env.EMAIL_ATTACHMENTS }}
          ignore_cert: true
          priority: normal
        env:
          EMAIL_SUBJECT: "Github Actions Workflow Started + Attachment"
          EMAIL_FROM: "Dana Tolman"
          EMAIL_BODY: "Build job of ${{github.repository}} initiated."
          EMAIL_TO: "danatolman@icloud.com"
          EMAIL_ATTACHMENTS: unified_report.html