name: GitHub Actions Workflow Email Test
on: [workflow_dispatch] # can add more than one event trigger
jobs:
  standard:
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions Workflow Started
          to: danatolman@icloud.com
          from: Dana Tolman
          body: Build job of ${{github.repository}} initiated.
          ignore_cert: true
          priority: normal

      - name: Announce process
        run: echo "Starting standard run"
  finished:
    needs: standard
    runs-on: ubuntu-latest
    steps:
      - name: Announce ending of process
        run: echo "ALL DONE! 🛑"