name: Locust Expressions Context Test
on: [workflow_dispatch] # can add more than one event trigger
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub Context
        run: echo "${{ toJSON(github) }}"

      - name: Output GitHub Issue Context
        run: echo "${{ toJson(github.event.issue) }}"

      - name: Output GitHub Issue Context for PR
        run: echo "${{ toJson(github.event.issue.pull_request) }}"

  standard:
    needs: info
    runs-on: ubuntu-latest
    steps:
      - name: Announce process
        run: echo "Running, but without container 🐍"

      - name: Get code
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip3 install --upgrade pip setuptools wheel
          pip3 install -r requirements.txt

      - name: Run locust test
        run: locust -f ./locustfiles/test.py -u 10 -r 2 --run-time 10 --headless --only-summary

  finished:
    needs: standard
    runs-on: ubuntu-latest
    steps:
      - name: Announce ending of process
        id: check_me
        run: echo "ALL DONE! 🛑
        continue-on-error: true

      - name: Was the previous test successful?
        run: echo "The previous test was successful!"
        if: steps.check_me.outcome == 'success'

      - name: The previous test failed
        run: echo "The previous test failed!"
        if: steps.check_me.outcome == 'failure'

        # https://docs.github.com/en/rest/guides/getting-started-with-the-rest-api?apiVersion=2022-11-28
        # https://docs.github.com/en/free-pro-team@latest/rest/actions/workflow-jobs?apiVersion=2022-11-28#download-job-logs-for-a-workflow-run
        # https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context
        # https://github.com/dctii/gh-actions-test/actions/runs/5815414506/job/15766941379