name: First Workflow
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: # if activity in this folder or file, permitted. paths-ignore is the opposite
      - '.github/workflows/first-action.yml'

jobs:
  first-job:
    environment: MY_NEW_ENV
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "Hello World!"
          echo "Hello again, World!"
      - name: Print goodbye
        run: |
          echo "Done - bye!"
          echo "Woops, forgot something. Ok, bye now!"

      - name: Print GUI-set environment var
        run: |
          echo "${{ vars.MY_NEW_VAR }}"

      - name: Print GUI-set made env var
        run: |
          echo "${{ vars.NEW_ENV_VAR }}"
          echo "$NEW_ENV_VAR"
          echo "${{ env.NEW_ENV_VAR }}"

  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print GUI-set environment var
        run: |
          echo "${{ vars.MY_NEW_VAR }}"

      - name: Print GUI-set made env var
        run: |
          echo "${{ vars.NEW_ENV_VAR }}"
          echo "$NEW_ENV_VAR"
          echo "${{ env.NEW_ENV_VAR }}"
