name: Locust Triggers Trial
on:
  workflow_dispatch:
  schedule:
    - cron: '30 18 * * *' # this will run at 10:30 AM Pacific Standard Time
jobs:
  time-teller:
    runs-on: ubuntu-latest
    steps:
      - name: Announce time
        run: echo "Current time in PST is $(TZ='America/Los_Angeles' date)"
  standard:
    needs: time-teller
    runs-on: ubuntu-latest
    steps:
      - name: Announce process
        run: echo "Running, but without container 🐍"

      - name: Get code
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip3 install --upgrade pip setuptools wheel
          pip3 install -r requirements.txt

      - name: Run locust test
        run: locust -f ./locustfiles/test.py -u 10 -r 2 --run-time 10 --headless --only-summary
  finished:
    needs: standard
    runs-on: ubuntu-latest
    steps:
      - name: Announce ending of process
        run: echo "ALL DONE! 🛑"